apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iqzs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-iqzs@sha256:803f3a49893247b73fc78f128a36e384c4285cdf89360533ccc87497e7f8530f
        name: my-nodejs
        resources: {}
status: {}
